In [1]:
import numpy as np

In [3]:
a = [1, 0, 0]
b = [0, 0, 0]

In [4]:
np.not_equal(a, b)

array([ True, False, False])

In [5]:
np.sum( np.not_equal(a, b) )

1

In [10]:
a[None]

TypeError: list indices must be integers or slices, not NoneType

In [13]:
a = np.arange(6).reshape(2,3)

In [14]:
a

array([[0, 1, 2],
       [3, 4, 5]])

In [19]:
a[None,:]

array([[[0, 1, 2],
        [3, 4, 5]]])

In [20]:
a[None,:,:]

array([[[0, 1, 2],
        [3, 4, 5]]])